openapi: 3.1.0
info:
  title: Example API
  version: 0.1.0
servers:
  - url: http://localhost:3000
components:
  schemas: {}
  parameters: {}
paths:
  /things/{thingId}:
    post:
      parameters:
        - schema:
            type: string
            pattern: "[\\d]+"
          required: true
          name: thingId
          in: path
        - schema:
            type: string
            pattern: "[\\d]+"
          required: false
          name: thingId
          in: query
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  pattern: "[a-z]+"
                description:
                  type: string
                  pattern: "[a-z]+"
              required:
                - name
                - description
      responses:
        "200":
          description: Create a thing
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    pattern: "[a-z]+"
                  description:
                    type: string
                    pattern: "[a-z]+"
                required:
                  - name
                  - description
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "415":
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message

